### ISSUE TITLE
How key/code values find their way into variable x?

### ISSUE THREAD

**Issue by mattster98** [towerclimber87/Wiegand-Keypad-ESP32#1]
Hey - I'm leveraging your yaml to interpret the keys of a wiegand keypad for a garage door opener.  I'm hoping to branch the code when the "#" key (comes in as key 11) is pressed, but there is no valid code entered so far.  I need to know both the current key, and the accumulated code, but in your code they both show up in "x".  I'm not able to see how/where these values make it into the variable x used in the debug output, and the lambda code.  x is used repeatedly, but seems to have different values.

Any pointers?  I assume I'm just slow. :)  Thanks!

**Comment by towerclimber87** [comment]
look at the following lines.
912
this provides sensors showing the # and *  pressed
1355-1357
this sends the single keys pressed


I added a new file V2.  take a look. I have updated the code to make it
easier to change the code.

**Comment by mattster98** [comment]
That's awesome, thanks for the fresh code!  I changed mine to send the code entered and the "action button" as separate entities and I'm getting what I need now.

**Comment by towerclimber87** [comment]
That is awesome and I’m always happy to help.
